### ISSUE TITLE
Edit-text boxes are oversized

### ISSUE THREAD

**Issue by grooveboxunited** [adithya-badidey/TW5-codemirror-plus#19]
The edit text box is oversized compared to default TiddlyWiki, to the point that it feels quite cumbersome.

To see this go to https://tiddlywiki.com/ and create a new tiddler. Then go to https://adithya-badidey.github.io/TW5-codemirror-plus/wiki.html and do the same. The empty text box is more appropriately sized in the first instance.

The same issue seems present in the settings. See "Default tiddlers" and "Text for new journal tiddlers" under Control Panel > Info > Basics.

**Comment by grooveboxunited** [comment]
Just realized that this is not a bug - the height of the text editor is just an editable option within TiddlyWiki. Normally its set to 400px but it just happens to be set to 600px in your demo.

**Comment by adithya-badidey** [comment]
I'm glad that got sorted out!
