### ISSUE TITLE
Better colours/design needed

### ISSUE THREAD

**Issue by adithya-badidey** [adithya-badidey/TW5-codemirror-plus#7]
There are too many colours right now - some more balancing will make the editor more aesthetic.

Maybe look at examples from https://ethanschoonover.com/solarized/

**Comment by jdjdjdjdjdjd** [comment]
In line with this, is there any chance your code will permit the usual CM theming mechanism? Maybe it will be better if your plugin will respond to CM color themes rather than to Tiddlywiki color palettes, since CM has such a wonderful library of colors already.

**Comment by adithya-badidey** [comment]
Fixed this in the release today. @jdjdjdjdjdjd Let me know what you think.
